### ISSUE TITLE
Add "ContactInfo" to the output

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfogenerator#12]
the page says:
"Copy the following line into your torrc configuration file and reload your tor daemon:"

which suggests that the output is a valid torrc config line, to meet that assumption lets add
"ContactInfo " at the beginning of the output

**Comment by erans** [comment]
I didn't think its a valid ContactInfo line, but let's see how people would react to it.

**Comment by nusenu** [comment]
Eran Sandler:
> I didn't think its a valid ContactInfo line

I think there is a slight misunderstanding.

"ContactInfo email:foo[]example.com foo" 

is a syntactically valid torrc line.


"email:foo[]example.com" 

is not.

My point was, that we should not ask people to add the later 
to their torrc (which the page effectively does currently) 
because that will result in (expected) failure.

**Comment by erans** [comment]
OK. I've added that.
