### ISSUE TITLE
move exit/non-exit radio button to the bottom + move DNS options into their own section

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfogenerator#5]
The 'Relay Type' selection is the first item on the list, by moving it to the bottom the user directly sees the impact of changing this value (new options appear).

Ideally the order would be:
* OS Information
* Relay Type selection
* DNS related fields (shown only in case of exits)

**Comment by erans** [comment]
So I moved all the DNS stuff into its own section. Now after OS information you have the relay type selection and if its an exit node it will show the new "DNS Information" section.
